idade = 11
idade = 11
system32= "minha idade "
#print ( system32 + str(idade))
idade1 = 11

#eu sou muito baixo!
LiamEBaixo =  str(1.39)
idade += float(LiamEBaixo)
#print ("minha altura " + str(LiamEBaixo) + " somada a minha idade, " + str(idade1) + " resulta em " + str(idade))

idadeboo = False
LiamEBaixoBoo = True

print ("minha idade esta " + str(idadeboo) + " e minha altura esta " + str (LiamEBaixoBoo))

